# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48b15c268a7327abb31885ea90339fc6425c22c33011e42fbdafe19b5e2c78ab81765dbdb7ed8514983da307a2acbbe979442d74e8837776fe02c973131d2aa3

test:
  secret_key_base: 6bce7ec810b5e71711b51d1c964f4266c7ff15f2270adad2ef366c2c69f8705e1a505dbcd4291081caa448254335c526b1294c4d1e75092fed45ef819ac1edec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
